default_language_version:
  python: python3

ci:
  autofix_prs: true

repos:
  # Run fast code improvement/checks before running PR specific helpers.
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .patch$
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: conda/recipes/mantid/meta.yaml|conda/recipes/mantid-developer/meta.yaml|conda/recipes/mantidqt/meta.yaml|conda/recipes/mantiddocs/meta.yaml|conda/recipes/mantidworkbench/meta.yaml
      - id: end-of-file-fixer
        exclude: .md5$|^external/|^tools/|Testing/Tools/cxxtest

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.5
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        args: ["--config", ".rstcheck.project.cfg"]
        exclude: |
          (?x)^(
          ^docs/source/index.rst$| # this has a value filled in by something
          ^docs/source/concepts/FittingMinimizersComparisonDetailed.rst| # strange ranking tags
          ^docs/source/fitting/.*|
          ^docs/source/techniques/.*
          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    # ruff must appear before black in the list of hooks
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        exclude: scripts/templates/reference/|Testing/Tools/cxxtest
