name: CI - Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  webtests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64
      - name: Checkout head
        uses: actions/checkout@v2
      - name: Run webtests
        run: chmod +x ./run_web_tests.sh && ./run_web_tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
